[package]
name = "furya_minter"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm_std = "1.5.0"
cosmwasm_storage = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
schemars = "0.9.1"

[lib]
crate-type = ["cdylib", "rlib"]
