[package]
name = "furya_nft_minter"
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8.16"
cw2 = "1.1"
cw_storage_plus = "1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
