[package]
name = "furya-nfts"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add your dependencies here
cosmwasm-std = { version = "1.0.0-beta1", features = ["staking"] }
cosmwasm-storage = { version = "1.0.0-beta1", features = ["iterator"] }
cosmwasm-schema = "1.0.0-beta1"
cosmwasm-derive = "1.0.0-beta1"
serde = { version = "1", features = ["derive"] }
schemars = "0.8.16"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# Add your custom features here

[package.metadata.docs.rs]
# Add metadata for documentation

[profile.dev]
codegen-units = 1
